export const actionTypes = {
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  UPLOAD_IMG_REQUEST: 'UPLOAD_IMG_REQUEST',
  UPLOAD_IMG_SUCCESS: 'UPLOAD_IMG_SUCCESS',
  UPLOAD_IMG_FAILURE: 'UPLOAD_IMG_FAILURE'
};
